# SPDX-License-Identifier: GPL-2.0

ifndef CONFIG_XPL_BUILD
obj-$(CONFIG_WEBUI_FAILSAFE) += qca_failsafe.o
obj-$(CONFIG_QCA_BOOTMENU) += cmd_qcaautoboot.o qca_bootmenu.o \
			      cmd_qcaboardboot.o cmd_qcaupgrade.o
endif
